version: "3"
services:
  api:
    build: ./backend
    ports:
      - "4040:4000"
    depends_on:
      - db
    container_name: blog-api
  client:
    image: nginx:1.16-alpine
    build: ./front
    ports:
      - "8080:80"
    container_name: blog-client
  db:
    image: postgres:13.1
    environment:
      POSTGRES_DB: "g20_db"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "password"
    ports:
      - "9432:5432"
    container_name: blog-db

  reverse-proxy:
    image: valian/docker-nginx-auto-ssl:1.0.0
    container_name: reverse-proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.ssl-data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: '12-2.casegames.ru'
      SITES: '12-2.casegames.ru=client:80;'
      FORCE_HTTPS: "true"
    depends_on:
      - client
      - api

volumes:
  .ssl-data:
